## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 0.6
notifications:
  email:
    - jonas.isensee@stud.uni-goettingen.de
    on_success: never
    on_failure: always
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("TimeseriesPrediction")'
